# Generated by Django 5.2 on 2025-04-13 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🛋️', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('device_type', models.CharField(choices=[('kettle', 'Чайник'), ('fridge', 'Холодильник'), ('tv', 'Телевізор'), ('washer', 'Пральна машина'), ('light', 'Освітлення'), ('climate', 'Клімат-контроль'), ('motion_sensor', 'Датчик руху'), ('gas_sensor', 'Датчик загазованості'), ('smoke_sensor', 'Датчик диму'), ('camera', 'Камера'), ('humidifier', 'Зволожувач повітря'), ('air_purifier', 'Очищувач повітря'), ('thermostat', 'Термостат'), ('smart_plug', 'Розумна розетка'), ('robot_vacuum', 'Робот-пилосос'), ('ventilation', 'Бризер / вентиляція')], max_length=50)),
                ('is_on', models.BooleanField(default=False)),
                ('brightness', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('target_temperature', models.FloatField(blank=True, null=True)),
                ('current_temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('target_humidity', models.FloatField(blank=True, null=True)),
                ('water_level', models.FloatField(blank=True, null=True)),
                ('air_quality', models.CharField(blank=True, max_length=50, null=True)),
                ('fan_speed', models.PositiveIntegerField(blank=True, null=True)),
                ('ionization', models.BooleanField(blank=True, null=True)),
                ('filter_status', models.CharField(blank=True, max_length=50, null=True)),
                ('airflow_speed', models.PositiveIntegerField(blank=True, null=True)),
                ('heating', models.BooleanField(blank=True, null=True)),
                ('boiling', models.BooleanField(blank=True, null=True)),
                ('wash_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('wash_time_left', models.PositiveIntegerField(blank=True, null=True)),
                ('triggered', models.BooleanField(blank=True, null=True)),
                ('recording', models.BooleanField(blank=True, null=True)),
                ('battery_level', models.PositiveIntegerField(blank=True, null=True)),
                ('cleaning_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('power_consumption', models.FloatField(blank=True, null=True)),
                ('schedule', models.JSONField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='smarthome.room')),
            ],
        ),
    ]
